export function unmangle(value: string) {
  return decodeURIComponent((value ?? '').toString());
}

export function toIcon(value: string) {
  if (value === null || value === undefined) return '';
  switch (value.toLocaleLowerCase()) {
    case 'txt':
      return 'mdi-text-box-outline';
    case 'epub':
      return 'mdi-book-open-variant';
    case 'cer':
    case 'crt':
    case 'pem':
    case 'pfx':
    case 'p12':
    case 'key':
      return 'mdi-file-certificate';
    case 'mp3':
    case 'wav':
    case 'ogg':
    case 'flac':
    case 'm4a':
      return 'mdi-file-music';
    case 'mp4':
    case 'avi':
    case 'mkv':
    case 'mov':
    case 'wmv':
    case 'flv':
    case 'webm':
    case 'mpeg':
    case 'mpg':
    case 'm4v':
      return 'mdi-file-video';
    case 'xml':
      return 'mdi-file-xml-box';
    case 'html':
    case 'xhtml':
    case 'htm':
      return 'mdi-language-html5';
    case 'js':
    case 'jsx':
      return 'mdi-language-javascript';
    case 'ts':
    case 'tsx':
      return 'mdi-language-typescript';
    case 'json':
    case 'json5':
    case 'yaml':
    case 'yml':
      return 'mdi-code-json';
    case 'md':
      return 'mdi-language-markdown';
    case 'eps':
    case 'gs':
    case 'pdf':
      return 'mdi-file-pdf-box';
    case 'svg':
    case 'png':
    case 'jpg':
    case 'gif':
    case 'jpeg':
    case 'bmp':
    case 'ico':
    case 'tiff':
    case 'tif':
      return 'mdi-file-image';
    case 'csv':
      return 'mdi-file-delimited';
    case 'xls':
    case 'xlsx':
    case 'ods':
      return 'mdi-file-excel';
    case 'doc':
    case 'docx':
    case 'odt':
      return 'mdi-file-word';
    case 'ppt':
    case 'pptx':
    case 'odp':
      return 'mdi-file-powerpoint';
    case 'zip':
    case '7z':
    case 'gz':
      return 'mdi-zip-box';
    case 'pl':
    case 'sh':
      return 'mdi-script-text-outline';
    case 'exe':
      return 'mdi-cog';
    case 'h':
    case 'c':
      return 'mdi-language-c';
    case 'cpp':
      return 'mdi-language-cpp';
    case 'css':
      return 'mdi-language-css3';
    case 'go':
      return 'mdi-language-go';
    case 'java':
    case 'class':
    case 'jar':
      return 'mdi-language-java';
    case 'kt':
      return 'mdi-language-kotlin';
    case 'php':
    case 'phar':
      return 'mdi-language-php';
    case 'py':
    case 'pyc':
      return 'mdi-language-python';
    case 'rs':
      return 'mdi-language-rust';
    default:
      return 'mdi-file-document-outline';
  }
}
