kind: pipeline
type: docker
name: backend

steps:
  - name: server:unit
    image: node:16
    commands:
      - cd nestjs
      - npm install
      - npm run lint
      - npm run test
      - npm run buildall

  - name: app:build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: phoenix741/woodstock-backup
      auto_tag: true

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: front:unit
    image: node:16
    commands:
      #- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      #- sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'
      #- apt update && apt install -y google-chrome-stable
      - cd front
      - npm install
      - npm run lint
      - npm run build
      #- npm run test:unit

  - name: front:build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: phoenix741/woodstock-backup-front
      dockerfile: ./front/Dockerfile
      context: ./front
      auto_tag: true

---
kind: pipeline
type: docker
name: website

steps:
  - name: website:build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: phoenix741/woodstock-backup-website
      dockerfile: ./website/Dockerfile
      context: ./website
      auto_tag: true

---
kind: pipeline
type: docker
name: final

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook
      channel: ci
    when:
      status: [success, failure]

depends_on:
  - backend
  - frontend
  - website
