[workspace]
members = [
  "backuppc-importer-rs",
  "cli-rs",
  "client-rs",
  "shared-rs",
  "woodstock-rs",
  "e2e-tests",
]
resolver = "2"

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.async-compression]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.sha3]
opt-level = 3

[profile.dev.package.blake3]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
#debug = true

[workspace.metadata.cross.build]
pre-build = ["apt-get install -y protobuf-compiler"]
