[workspace]
members = [ "backuppc_importer","clientrs"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[workspace.metadata.cross.build]
pre-build = ["apt-get install -y protobuf-compiler"]
