services:
  website:
    build:
      context: ./docs/website
      dockerfile: Dockerfile
    image: phoenix741/woodstock-backup-website:develop
    ports:
      - 8080:80
  woodstock:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=1
        - NODE_VERSION=20-slim
        - DEBIAN_VERSION=debian:12-slim
    image: phoenix741/woodstock-backup:develop
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=debug
      - NODE_ENV=development
      - BACKUP_PATH=/backups
    volumes:
      - "backups_storage:/backups"

  woodstock_client:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=1
        - NODE_VERSION=20-slim
        - DEBIAN_VERSION=debian:12-slim
      target: client
    image: phoenix741/woodstock-backup-client:develop
    ports:
      - 3657:3657
    environment:
      - LOG_LEVEL=debug
    volumes:
      - "client_storage:/etc/woodstock"

  # woodstock_client:
  #   image: phoenix741/woodstock-backup:develop
  #   command: /nestjs/apps/client/main.js
  #   environment:
  #     - LOG_LEVEL=debug
  #     - NODE_ENV=development

  redis:
    image: "bitnami/redis:7.4"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  prometheus:
    image: bitnami/prometheus:2
    volumes:
      - prometheus_storage:/opt/bitnami/prometheus/data
      - ./docker/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    network_mode: "host"

volumes:
  redis_data:
  prometheus_storage:
  client_storage:
  backups_storage:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/woodstock
      o: bind
