@startuml
start

if (first configuration?) then (yes)
    #LightBlue:Wait for local configuration;
    -[#blue,dashed]-> configuration available;

    :Create machine uuid;
    :Get schedule configuration;
endif

repeat
#LightBlue:Sleep & Wait for next schedule;
-[#blue,dashed]-> @schedule;
:Get configuration;
:Get backup number information;

if (backup number != remote backup number || ! backup number) then (yes)
:Get last backups content;
endif

fork
    :Search for files;
    if (file modified?) then (yes)
        :Add chunk to Transfert;
        :Transfert file manifest;
    endif
fork again
    while (chunk available?) 
        #LightBlue:Wait for chunk to send;
        -[#blue,dashed]-> chunk available;
        :Check if chunk already exists;
        if (!exist || check content?) then (yes)
            :Transfert chunk;
        endif
    endwhile
end fork
repeat while (not stopped)

stop
@enduml