use std::{io, path::Path, pin::Pin};

use futures::Stream;

use crate::{pool::ChunkDescriptor, proto::ProtobufReader};

/// Reads a staging file produced by [`StagingWriter`].
///
/// A staging file is a flat, non-compressed sequence of length-delimited
/// [`ChunkDescriptor`] protobuf messages.  It lives in the backup directory
/// alongside the `REFCNT` file and records every chunk encountered during the
/// backup (duplicates included).
///
/// Use [`StagingWriter::compact`] to aggregate duplicates before integrating
/// the staging data into the pool index.
pub struct StagingReader {
    inner: ProtobufReader<ChunkDescriptor>,
}

impl StagingReader {
    /// Opens an existing staging file for reading.
    ///
    /// # Arguments
    /// * `path` - Full path to the staging file (e.g. `<backup_dir>/staging.idx`).
    ///
    /// # Errors
    /// Returns an error if the file cannot be opened.
    pub async fn open(path: &Path) -> io::Result<Self> {
        let inner = ProtobufReader::new(path, false).await?;
        Ok(Self { inner })
    }

    /// Returns an async stream over all [`ChunkDescriptor`] entries in the file.
    ///
    /// Entries are yielded in the order they were written (insertion order).
    /// Callers that need deduplicated data should use [`read_to_end`](Self::read_to_end)
    /// followed by manual aggregation, or call [`StagingWriter::compact`] first.
    pub fn into_stream(
        &mut self,
    ) -> Pin<Box<dyn Stream<Item = io::Result<ChunkDescriptor>> + Send + Sync + '_>> {
        self.inner.into_stream()
    }

    /// Reads all [`ChunkDescriptor`] entries from the staging file into `out`.
    ///
    /// # Returns
    /// The number of entries appended to `out`.
    ///
    /// # Errors
    /// Returns an error if reading or decoding fails.
    pub async fn read_to_end(&mut self, out: &mut Vec<ChunkDescriptor>) -> io::Result<usize> {
        self.inner.read_to_end(out).await
    }
}

#[cfg(test)]
mod tests {
    use futures::StreamExt;

    use super::*;

    /// Helper: check that the staging file written by the writer tests can be
    /// streamed correctly.  The file is created by `staging_writer` tests.
    #[tokio::test]
    async fn test_read_stream_after_compact() {
        // This file is generated by `staging_writer::tests::test_compact`.
        // If it does not exist yet (e.g. CI order), the test is simply skipped.
        let path = std::path::PathBuf::from("./data/staging_compact.idx");
        if !path.exists() {
            return;
        }

        let mut reader = StagingReader::open(&path).await.unwrap();
        let stream = reader.into_stream();
        futures::pin_mut!(stream);

        let mut count = 0usize;
        while let Some(entry) = stream.next().await {
            let _ = entry.unwrap();
            count += 1;
        }

        // After compact, the two identical hashes must have been merged → 2 entries.
        assert_eq!(count, 2);
    }
}
