#!/usr/bin/env bash
# SSH/SCP helpers for driving the virtual machines.
#
# Every guest — Debian, FreeBSD and Windows (OpenSSH Server) — is reachable the
# same way: as root/Administrator over the per-VM host port forward, with the
# key pair generated by images/build-common.sh.

SSH_OPTS=(
    -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null
    -o LogLevel=ERROR
    -o ConnectTimeout=10
    -o ServerAliveInterval=15
    -o ServerAliveCountMax=4
)

# Host port for a VM role: server | debian | freebsd | windows
vm_port() {
    case "$1" in
        server)  echo "${PORT_SSH_SERVER}"  ;;
        debian)  echo "${PORT_SSH_DEBIAN}"  ;;
        freebsd) echo "${PORT_SSH_FREEBSD}" ;;
        windows) echo "${PORT_SSH_WINDOWS}" ;;
        *) die "unknown VM role: $1" ;;
    esac
}

vm_user() {
    case "$1" in
        windows) echo "Administrator" ;;
        *)       echo "root" ;;
    esac
}

# Lab-network address of a VM role.
vm_ip() {
    case "$1" in
        server)  echo "${IP_SERVER}"  ;;
        debian)  echo "${IP_DEBIAN}"  ;;
        freebsd) echo "${IP_FREEBSD}" ;;
        windows) echo "${IP_WINDOWS}" ;;
        *) die "unknown VM role: $1" ;;
    esac
}

# Every remote call is wrapped in `timeout`: a command that hangs inside a guest
# would otherwise stall the whole suite with no output at all. Exit code 124
# then means "the VM stopped answering", which is a far more useful failure than
# an indefinite wait.

# ssh_run <role> <command...>  — run a command in the VM, stdout passed through.
#
# Windows output is stripped of carriage returns. PowerShell ends every line
# with CRLF, so an exact comparison against it (`assert_output`) fails in the
# most confusing way possible — reporting «expected 'Automatic', got
# 'Automatic'». The exit status still comes from ssh, not from tr.
ssh_run() {
    local role="$1"; shift
    if [[ "${role}" == "windows" ]]; then
        timeout "${SSH_TIMEOUT}" ssh "${SSH_OPTS[@]}" -i "${SSH_KEY}" -p "$(vm_port "${role}")" \
            "$(vm_user "${role}")@127.0.0.1" "$@" | tr -d '\r'
        return "${PIPESTATUS[0]}"
    fi
    timeout "${SSH_TIMEOUT}" ssh "${SSH_OPTS[@]}" -i "${SSH_KEY}" -p "$(vm_port "${role}")" \
        "$(vm_user "${role}")@127.0.0.1" "$@"
}

# ssh_script <role>  — run a shell script read from stdin inside the VM.
# Preferred over ssh_run for anything with quoting, pipes or heredocs.
ssh_script() {
    local role="$1"
    timeout "${SSH_TIMEOUT}" ssh "${SSH_OPTS[@]}" -i "${SSH_KEY}" -p "$(vm_port "${role}")" \
        "$(vm_user "${role}")@127.0.0.1" "bash -euo pipefail -s"
}

# ps_script <role>  — same, for a PowerShell script (Windows guests).
#
# -ExecutionPolicy Bypass is required, not cosmetic: the default policy is
# Restricted, so any script that invokes a .ps1 by path dies with
# "running scripts is disabled on this system" — which under `set -e` aborts the
# whole suite rather than failing one assertion.
ps_script() {
    local role="$1"
    timeout "${SSH_TIMEOUT}" ssh "${SSH_OPTS[@]}" -i "${SSH_KEY}" -p "$(vm_port "${role}")" \
        "$(vm_user "${role}")@127.0.0.1" \
        "powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command -" | tr -d '\r'
    return "${PIPESTATUS[0]}"
}

# scp_to <role> <local> <remote>
# Copying the packages takes a while, hence the larger allowance.
scp_to() {
    local role="$1" src="$2" dst="$3"
    timeout $(( SSH_TIMEOUT * 3 )) scp "${SSH_OPTS[@]}" -i "${SSH_KEY}" -P "$(vm_port "${role}")" -r \
        "${src}" "$(vm_user "${role}")@127.0.0.1:${dst}"
}

# scp_from <role> <remote> <local>
scp_from() {
    local role="$1" src="$2" dst="$3"
    timeout $(( SSH_TIMEOUT * 3 )) scp "${SSH_OPTS[@]}" -i "${SSH_KEY}" -P "$(vm_port "${role}")" -r \
        "$(vm_user "${role}")@127.0.0.1:${src}" "${dst}"
}

# Block until the VM answers SSH, or fail after $BOOT_TIMEOUT.
#
# The probe is `exit 0`, not `true`: the Windows guest runs PowerShell as its
# login shell, which has no `true` command, so a healthy Windows VM answered
# every probe with a non-zero status and was declared unreachable after the full
# BOOT_TIMEOUT. `exit 0` means the same thing to both shells.
wait_ssh() {
    local role="$1"
    log "waiting for SSH on ${role} (port $(vm_port "${role}"))"
    if retry "${BOOT_TIMEOUT}" 5 ssh_run "${role}" "exit 0" >/dev/null 2>&1; then
        log "${role} is up"
        return 0
    fi
    die "${role} did not answer SSH within ${BOOT_TIMEOUT}s"
}
