name: CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          cd nestjs
          npm ci
          npm run lint
          npm run test
          npm run buildall

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: |
          cd front
          npm ci
          npm run lint
          npm run build

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'promote' && github.event.action == 'published' && github.ref == 'refs/tags/v*'
    steps:
      - uses: actions/checkout@v3

      - name: Build website
        uses: docker/build-push-action@v2
        with:
          context: ./docs/website
          file: ./docs/website/Dockerfile
          push: true
          tags: phoenix741/woodstock-backup-website:latest

      - name: Build server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: phoenix741/woodstock-backup:latest

  notify:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
      - publish
    if: always()
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
