name: CI/CD

on:
  pull_request:

jobs:
  start:
    runs-on: ubuntu-latest
    outputs:
      message_id: ${{ steps.slack.outputs.message_id }}
    steps:
      - name: Notify slack success
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: https://github.com/voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ci
          status: STARTING
          color: warning

  backend:
    runs-on: ubuntu-latest
    needs:
      - start

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - run: "apt-get update && apt-get install -y git-lfs"
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd nestjs
          npm ci
          npm run lint
          npm run test
          npm run buildall

  frontend:
    runs-on: ubuntu-latest
    needs:
      - start
    steps:
      - run: "apt-get update && apt-get install -y git-lfs"
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: |
          cd front
          npm ci
          npm run lint
          npm run build

  notify:
    runs-on: ubuntu-latest
    needs:
      - start
      - backend
      - frontend
    if: ${{ always() }}
    steps:
      #- run: "echo ${{ toJSON(needs) }}"
      - name: Notify slack success
        if: "${{ always() && (needs.backend.result == 'success' && needs.frontend.result == 'success') }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: https://github.com/voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ needs.start.outputs.message_id }}
          channel: ci
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: "${{ always() && (needs.backend.result == 'failure' || needs.frontend.result == 'failure') }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: https://github.com/voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ needs.start.outputs.message_id }}
          channel: ci
          status: FAILED
          color: danger
