name: Release

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
  push:
    branches:
      - "master"
      - "main"
      - "alpha"
      - "beta"

jobs:
  prerelease:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        if: github.event_name == 'push'
        run: |
          apt-get update
          apt-get install -y git-lfs jq

      - name: Checkout project
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Node.js
        if: github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install dependencies
        if: github.event_name == 'push'
        run: npm ci

      - name: Calculate next version
        if: github.event_name == 'push'
        id: next_version
        run: |
          npx semantic-release --dry-run | tee semantic_release_output.txt
          NEXT_VERSION=$(grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+' semantic_release_output.txt)
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

  unittest:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y protobuf-compiler cmake make build-essential git-lfs libacl1-dev libfuse-dev

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Unit test (release)
        run: cargo test --release -- --nocapture
        env:
          RUST_LOG: debug

      - name: Install Node.JS dependencies
        run: |
          npm ci

      - name: Build shared (rust + nodejs)
        run: |
          cd shared-rs
          npm run build
          cd ..

      - name: Build server
        run: |
          cd nestjs
          npm run lint
          npm run test
          npm run buildall
          cd ..

      - name: Build front
        run: |
          cd front
          npm run lint
          npm run build
          cd ..

  clientrs:
    needs: [prerelease]
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: --features all
            binary_name: binaries-linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: --no-default-features --features "client,pool,server,fuse_unix"
            binary_name: binaries-linux-lite
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            features: --no-default-features --features "client,pool,server"
            binary_name: binaries-windows
        # Disabled musl target for (depending of libm, libc,...)
        # - os: ubuntu-latest
        #   target: x86_64-unknown-linux-musl
        # need dependencies: # musl-dev musl-tools

    steps:
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt-get update
          apt-get install -y protobuf-compiler cmake make build-essential git-lfs libacl1-dev libfuse-dev zip

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          cache: true

      - name: Mise à jour des versions
        if: github.event_name == 'push'
        run: |
          cargo install cargo-workspaces
          cargo workspaces version --all ${{ steps.next_version.outputs.NEXT_VERSION }}

      - name: Build (release)
        run: cargo build --verbose --release --target ${{ matrix.target }} ${{ matrix.features }}

      - name: Archive binary
        run: |
          mkdir zipfile
          cd target/${{ matrix.target }}/release
          cp ws_client_daemon* ../../../zipfile
          cp ws_console* ../../../zipfile
          cp ws_backuppc_importer* ../../../zipfile

      - name: Archive binary (Linux)
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd zipfile
          find . -type f \( -name "*.d" -o -name "*.pdb" \) -delete
          zip -r "${{ matrix.binary_name }}-${{ matrix.target }}.zip" *

      - name: Archive binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd zipfile
          powershell -Command "Get-ChildItem -Path * -Exclude *.d,*.pdb | Compress-Archive -DestinationPath ${{ matrix.binary_name }}-${{ matrix.target }}.zip"

      - name: Upload artifacts
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: |
            zipfile/${{ matrix.binary_name }}-${{ matrix.target }}.zip

  upload:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    needs: [clientrs, unittest]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git-lfs jq

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          cache: true

      - name: Installation de cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Download artifacts
        uses: christopherhx/gitea-download-artifact@v4

      - name: Import GPG key
        if: github.event_name == 'push'
        id: import-gpg
        uses: https://github.com/crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          fingerprint: 0C69E9FC3A34B91A
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        if: github.event_name == 'push'
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Display structure of downloaded files
        if: github.event_name == 'push'
        run: |
          mkdir zipfile
          mv ./binaries-*/* ./zipfile/
          cd ./zipfile
          shasum --algorithm 256 --binary ./* | tee ./SHA256SUM.txt
          cat ./SHA256SUM.txt
          for file in *; do
            gpg --batch --yes --armor --detach-sign "$file"
          done

      - name: Release
        if: github.event_name == 'push'
        env:
          GITEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITEA_URL: https://gogs.shadoware.org
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
        run: npx semantic-release

  debian_rs:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    needs: [upload]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y protobuf-compiler cmake make build-essential git-lfs libacl1-dev libfuse-dev

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          cache: true

      - name: Installation de cargo-deb
        run: cargo install cargo-deb

      - name: Generate debian package
        run: |
          cargo deb -p woodstock-client-rs --target ${{ matrix.target }}
          cargo deb -p woodstock-cli-rs --target ${{ matrix.target }}
          cargo deb -p ws_backuppc_importer --target ${{ matrix.target }}

      - name: Publish package to debian gitea repository
        if: github.event_name == 'push'
        run: |
          for file in target/${{ matrix.target }}/debian/*.deb; do
            curl --user "phoenix:${{ secrets.RELEASE_TOKEN }}" \
              --upload-file $file \
              https://gogs.shadoware.org/api/packages/ShadowareOrg/debian/pool/bookworm/main/upload
          done

  docker:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    needs: [upload]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_version: 1
            node_version: 20-slim
            features: --features all
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git-lfs

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Get version from package.json
        id: version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Get metadata to tag container image
        if: github.event_name == 'push'
        uses: https://github.com/docker/metadata-action@v4
        id: meta
        with:
          context: git
          # Liste des images Docker à utiliser comme base pour les tags
          images: |
            phoenix741/woodstock-backup
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.version }}

      - name: Get metadata to tag container image
        if: github.event_name == 'push'
        uses: https://github.com/docker/metadata-action@v4
        id: meta-website
        with:
          context: git
          # Liste des images Docker à utiliser comme base pour les tags
          images: |
            phoenix741/woodstock-backup-website
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.version }}

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Server Docker Image
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          file: Dockerfile
          context: .
          load: true
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RUST_VERSION=${{matrix.rust_version}}
            NODE_VERSION=${{matrix.node_version}}
            FEATURES=${{matrix.features}}

      - name: Build Website Docker Image
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          file: ./docs/website/Dockerfile
          context: ./docs/website
          load: true
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta-website.outputs.tags }}
          labels: ${{ steps.meta-website.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
