name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_version: 1
            node_version: 20-slim
            features: --features all
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Get metadata to tag container image
        uses: https://github.com/docker/metadata-action@v4
        id: meta
        with:
          context: git
          # Liste des images Docker à utiliser comme base pour les tags
          images: |
            phoenix741/woodstock-backup

      - name: Get metadata to tag container image
        uses: https://github.com/docker/metadata-action@v4
        id: meta-website
        with:
          context: git
          # Liste des images Docker à utiliser comme base pour les tags
          images: |
            phoenix741/woodstock-backup-website

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Server Docker Image
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          file: Dockerfile
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RUST_VERSION=${{matrix.rust_version}}
            NODE_VERSION=${{matrix.node_version}}
            FEATURES=${{matrix.features}}

      - name: Build Website Docker Image
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          file: ./docs/website/Dockerfile
          context: ./docs/website
          load: true
          tags: ${{ steps.meta-website.outputs.tags }}
          labels: ${{ steps.meta-website.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
