name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'promote' && github.event.action == 'published' && github.ref == 'refs/tags/v*'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build website
        uses: docker/build-push-action@v2
        with:
          context: ./docs/website
          file: ./docs/website/Dockerfile
          push: true
          tags: phoenix741/woodstock-backup-website:latest

      - name: Build server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: phoenix741/woodstock-backup:latest

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: https://github.com/voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ needs.start.steps.slack.outputs.message_id }}
          channel: ci
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: https://github.com/voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ needs.start.steps.slack.outputs.message_id }}
          channel: ci
          status: FAILED
          color: danger
