[package]
name = "ws_backuppc_importer"
description = "Woodstock BackupPC Importer"
version = "2.1.0-alpha.5"
edition = "2021"
authors = ["Ulrich Vandenhekke <ulrich.vdh@gmail.com>"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = { workspace = true }
backuppc_pool_reader = "^2.0"
chrono.workspace = true
clap = { workspace = true }
color-eyre = { workspace = true }
console = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lru = { workspace = true }
sha3 = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
woodstock-rs = { workspace = true }
uuid = { workspace = true }
