---
tools:
  df: /usr/bin/df
  btrfs: /usr/bin/btrfs
  compsize: /usr/sbin/compsize
  ping: /usr/bin/ping
  nmblookup: /usr/bin/nmblookup
  ssh: /usr/bin/ssh
  rsync: /usr/bin/rsync
  stat: /usr/bin/stat

command:
  rsh: "${ssh} -o stricthostkeychecking=no -o userknownhostsfile=/dev/null -o batchmode=yes -o passwordauthentication=no"
  ping: "${ping} -c 1 ${ip}"
  resolveNetbiosFromHostname: "${nmblookup} ${hostname}"
  resolveNetbiosFromIP: "${nmblookup} -A ${ip}"
  getFilesystem: "${stat} -f --format=%T ${hostPath}"
  statsSpaceUsage: "${df} -k --print-type ${hostPath}"
  statsDiskUsage: "${btrfs} qgroup show --raw ${hostPath}"
  btrfsQGroupEnable: "${btrfs} quota enable"
  btrfsBackupQGroupCreate: "${btrfs} qgroup create 1/${qGroupId} ${hostPath}"
  btrfsVersion: "${btrfs} version"
  btrfsListSubvolume: "${btrfs} subvolume list -t ${hostPath}"
  btrfsCreateSubvolume: "${btrfs} subvolume create -i 1/${qGroupId} ${destBackupPath}"
  btrfsCreateSnapshot: "${btrfs} subvolume snapshot -i 1/${qGroupId} ${srcBackupPath} ${destBackupPath}"
  btrfsDeleteSnapshot: "${btrfs} subvolume delete ${destBackupPath}"
  btrfsMarkROSubvolume: "${btrfs} property set -ts ${destBackupPath} ro true"
  btrfsMarkRWSubvolume: "${btrfs} property set -ts ${destBackupPath} ro false"
  btrfsGetCompressionSize: "${compsize} -b ${destBackupPath}"

paths:
  qgroupHostPath: "${hostPath}/${hostname}/qgroup"
  srcBackupPath: "${hostPath}/${hostname}/${srcBackupNumber}"
  destBackupPath: "${hostPath}/${hostname}/${destBackupNumber}"
