[package]
name = "e2e-tests"
version = "2.1.0-alpha.12"
edition = "2021"

[dependencies]
woodstock-rs = { path = "../woodstock-rs" }
woodstock-client-rs = { path = "../client-rs" }

eyre = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
hyper-util = { workspace = true }
tracing = { workspace = true }
tower = { workspace = true, features = ["util"] }
tonic = { workspace = true, features = ["tls-native-roots", "gzip"] }
uuid = { workspace = true }

[dev-dependencies]
