[package]
edition = "2021"
name = "woodstock_shared-rs"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.0", default-features = false, features = ["napi8"] }
napi-derive = "2.12.2"
tempfile = "3.2.0"
flate2 = "1.0"
# tonic can be used if we need to use grpc
prost = "0.11"

[dependencies.uuid]
version = "1.3.3"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[build-dependencies]
napi-build = "2.0.1"
prost-build = { version = "0.11" }

[profile.release]
lto = true

