/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class Manifest {
  manifestPath: string
  fileListPath: string
  journalPath: string
  newPath: string
  lockPath: string
  constructor(manifestName: string, path: string)
}
