//! Redis-backed session and login-flow storage for the OIDC BFF flow.
//!
//! Two kinds of short-lived state live in Redis, both under the `woodstock:auth:` prefix
//! (consistent with the existing `woodstock:cache:*` convention):
//!
//! - A **login flow** (`flow:{state}`): the PKCE verifier, nonce, and `return_to` URL
//!   generated by `/auth/login`, consumed exactly once by `/auth/callback`.
//! - A **session** (`session:{sid}`): the authenticated identity, valid for
//!   `session_ttl_secs`, looked up on every request via the session cookie.
//!
//! `owned_hosts` is deliberately not part of either — it is resolved fresh from
//! [`woodstock::config::Hosts`] on every request (see [`crate::auth::middleware`]), so
//! editing a host's `owners` in its YAML file never has to wait out a session's TTL, only
//! `Hosts`'s own (much shorter to fix) cache.

use rand::Rng;
use redis::AsyncCommands;
use serde::{Deserialize, Serialize};
use tracing::warn;

use crate::api::ApiError;

const FLOW_TTL_SECS: u64 = 600;

fn flow_key(state: &str) -> String {
    format!("woodstock:auth:flow:{state}")
}

fn session_key(sid: &str) -> String {
    format!("woodstock:auth:session:{sid}")
}

/// Generates a random URL-safe token (32 bytes of entropy) used for both the CSRF
/// `state` parameter and session IDs.
fn random_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    use base64::Engine;
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
}

#[derive(Debug, Serialize, Deserialize)]
struct FlowData {
    pkce_verifier: String,
    nonce: String,
    return_to: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionData {
    pub subject: String,
    pub identity: String,
    /// Captured from the ID token at login and never re-checked against the IdP for the
    /// life of the session — unlike `owned_hosts` (deliberately excluded from this struct,
    /// see the module doc comment), there is no cheap local source of truth to re-derive
    /// this from on every request. Revoking someone's admin role on the IdP therefore only
    /// takes effect the next time they log in, bounded by `session_ttl_secs`
    /// (`OIDC_SESSION_TTL_SECS`) — documented in `docs/developer_guide/AUTHENTICATION.md`.
    pub is_admin: bool,
    /// The raw ID token issued at login, kept only so `/auth/logout` can pass it as
    /// `id_token_hint` to the IdP's end-session endpoint (see
    /// [`super::oidc::OidcClient::end_session_url`]) — without it, logging out of Woodstock
    /// Backup leaves the IdP's own SSO session alive, and the next login silently
    /// re-authenticates the same person instead of prompting them.
    pub id_token: String,
}

/// Stores the PKCE verifier/nonce/return URL for an in-flight login, keyed by the OIDC
/// CSRF `state` token already embedded in the authorization URL by
/// [`super::oidc::OidcClient::authorization_request`] — so `/auth/callback`'s `state`
/// query parameter is exactly the lookup key, single use, `FLOW_TTL_SECS` TTL.
pub async fn create_flow(
    redis_client: &redis::Client,
    state: &str,
    pkce_verifier: String,
    nonce: String,
    return_to: String,
) -> Result<(), ApiError> {
    let mut conn = redis_client.get_multiplexed_async_connection().await?;
    let payload = serde_json::to_string(&FlowData {
        pkce_verifier,
        nonce,
        return_to,
    })?;
    conn.set_ex::<_, _, ()>(flow_key(state), payload, FLOW_TTL_SECS)
        .await?;
    Ok(())
}

/// Consumes (atomically reads-and-deletes, via `GETDEL`) the flow for `state`. Returns
/// `None` if the state is unknown, expired, or already consumed — the caller should treat
/// this as a rejected callback (invalid/replayed/expired login attempt), not retry.
///
/// `GETDEL` matters here, not just a plain `GET` then `DEL`: two concurrent callbacks for
/// the same `state` (a browser retry, a prefetched callback URL) must not both be able to
/// read the flow before either deletes it — that would let the same PKCE verifier/nonce be
/// used twice, which the "exactly once" framing of this function promises callers.
pub async fn consume_flow(
    redis_client: &redis::Client,
    state: &str,
) -> Option<(String, String, String)> {
    let mut conn = redis_client.get_multiplexed_async_connection().await.ok()?;
    let raw: Option<String> = conn.get_del(flow_key(state)).await.ok()?;
    let flow: FlowData = serde_json::from_str(&raw?).ok()?;
    Some((flow.pkce_verifier, flow.nonce, flow.return_to))
}

/// Creates a session for an authenticated identity, returns the session ID to set as the
/// cookie value.
pub async fn create_session(
    redis_client: &redis::Client,
    data: &SessionData,
    ttl_secs: u64,
) -> Result<String, ApiError> {
    let sid = random_token();
    let mut conn = redis_client.get_multiplexed_async_connection().await?;
    let payload = serde_json::to_string(data)?;
    conn.set_ex::<_, _, ()>(session_key(&sid), payload, ttl_secs)
        .await?;
    Ok(sid)
}

/// Loads a session by ID. Returns `None` on any error (missing, expired, Redis
/// unavailable, corrupt payload) — all of which mean "treat this request as
/// unauthenticated", not a hard failure.
pub async fn load_session(redis_client: &redis::Client, sid: &str) -> Option<SessionData> {
    let mut conn = redis_client.get_multiplexed_async_connection().await.ok()?;
    let raw: Option<String> = conn.get(session_key(sid)).await.ok()?;
    serde_json::from_str(&raw?).ok()
}

/// Deletes a session (logout). Best-effort: a Redis failure here just means the session
/// outlives the user's click on "logout" until its TTL naturally expires.
pub async fn delete_session(redis_client: &redis::Client, sid: &str) {
    if let Ok(mut conn) = redis_client.get_multiplexed_async_connection().await {
        if let Err(e) = conn.del::<_, ()>(session_key(sid)).await {
            warn!("Failed to delete session on logout: {e}");
        }
    }
}
