[package]
name = "woodstock-cli-rs"
description = "Woodstock Tools"
version = "2.0.0-alpha.58"
edition = "2021"
authors = ["Ulrich Vandenhekke"]
license = "MIT"

[package.metadata.deb]
license-file = ["../LICENSE", "0"]

[features]
default = ["fuse_unix"]
fuse_unix = ["dep:lru", "dep:twox-hash", "dep:libc", "dep:fuser", "dep:rand"]

[[bin]]
name = "ws_console"
path = "src/console.rs"

[[bin]]
name = "ws_sync"
path = "src/wssync.rs"

[[bin]]
name = "ws_restore"
path = "src/wsrestore.rs"

[dependencies]
async-stream = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
console = { workspace = true }
eyre = { workspace = true }
async-compression = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
woodstock-rs = { workspace = true }
chrono.workspace = true
redis = { workspace = true }
uuid = { workspace = true }

# Fuse dependencies
[target.'cfg(unix)'.dependencies]
lru = { workspace = true, optional = true }
twox-hash = { version = "^2.1", optional = true }
libc = { version = "^0.2", optional = true }
fuser = { version = "0.17", optional = true }
rand = { workspace = true, optional = true }
