---
tools:
  df: /bin/df
  nmblookup: /usr/bin/nmblookup
  stat: /usr/bin/stat

command:
  resolveNetbiosFromHostname: "${nmblookup} ${hostname}"
  resolveNetbiosFromIP: "${nmblookup} -A ${ip}"
  statsSpaceUsage: "${df} -k --print-type ${hostPath}"
