[package]
name = "woodstock-client-rs"
description = "Woodstock client daemon"
version = "2.0.0-alpha.48"
edition = "2021"
authors = ["Ulrich Vandenhekke"]
license = "MIT"
build = "build.rs"

[package.metadata.deb]
license-file = ["../LICENSE", "0"]
maintainer-scripts = "debian/"
systemd-units = { enable = true }
conf-files = ["/etc/woodstock/config.yml"]
assets = [
    # binary
    ["target/release/ws_client_daemon", "usr/bin/", "755"],
    # assets
    ["debian/config.yaml", "/etc/woodstock/config.yaml", "0600"],
]

[features]
default = ["mdns", "acl", "xattr"]
acl = ["dep:posix-acl"]
xattr = ["dep:xattr"]
mdns = ["woodstock-rs/mdns", "dep:mdns-sd"]

[lib]
name = "woodstock_client_rs"
path = "src/lib.rs"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "ws_client_daemon"
path = "src/main.rs"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "ws_client_console"
path = "src/console.rs"

[dependencies]
async-stream = "^0.3"
clap = { version = "^4.5", features = ["derive"] }
color-eyre = "^0.6"
dirs = "^6.0"
env_logger = "^0.11"
eyre = "^0.6"
fern = "0.6"
futures = "^0.3"
globset = "^0.4"
hex = { version = "^0.4", features = ["serde"] }
hostname = "^0.4"
if-addrs = "0.13.3"
jsonwebtoken = "^9.3"
lazy_static = "^1.5"
libc = "0.2.161"
log = { version = "^0.4", default-features = false, features = [
    "std",
    "max_level_debug",
    "release_max_level_info",
] }
mdns-sd = { version = "^0.13", optional = true }
multi_log = "^0.1"
rand = "^0.9"
reqwest = { version = "0.12.9", features = ["json", "rustls-tls-native-roots"] }
shlex = { version = "^1.3" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "^0.9"
self_update = { git = "https://github.com/phoenix741/self_update.git", branch = "feature/prerelease", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
semver = "^1.0"
tokio = { version = "^1.40", features = [
    "fs",
    "macros",
    "rt-multi-thread",
    "signal",
    "process",
] }
tokio-stream = "^0.1"
ring = { version = "0.17" }
rustls = { version = "0.23", features = ["ring","logging","tls12"], default-features = false }
tonic = { version = "^0.13", features = ["tls-ring", "tls-webpki-roots", "gzip"] }
uuid = { version = "^1.10", features = ["v4", "fast-rng", "macro-diagnostics"] }
woodstock-rs = { path = "../woodstock-rs", default-features = false }
tempfile = "3.20.0"
chrono = "0.4.41"
serde-env = "0.2.0"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "^0.30", features = ["fs"] }
xattr = { version = "^1.3", optional = true }
posix-acl = { version = "^1.2", optional = true }
mnt = "0.3.1"

[target.'cfg(windows)'.dependencies]
winlog = "0.2"
windows-service = "^0.8"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "^0.60"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Power",
    "Win32_System_RemoteDesktop",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_UI_WindowsAndMessaging",
]

[target.'cfg(windows)'.dependencies.windows]
version = "^0.61"
features = [
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_Vss",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_NetworkManagement_WindowsFirewall",
]

[target.'cfg(windows)'.build-dependencies]
windows_exe_info = "0.5"
