query Host($hostname: String!) {
  host(hostname: $hostname) {
    name
    agentVersion
    lastBackup {
      agentVersion
      status
    }
    availibilityState
    timeSinceLastBackup
    dateToNextBackup
    addresses
    configuration {
      operations {
        preCommands {
          command
        }
        operation {
          shares {
            name
          }
        }
        postCommands {
          command
        }
      }
      schedule {
        activated
      }
    }
  }
}
